//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {

        public int empID { get; set; }
        public string empName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public employee()
        {  }

        public employee(int empID, string empName, string email, string phone, string city)
        {
            this.empID = empID;
            this.empName = empName;
            this.email = email;
            this.phone = phone;
            this.city = city;
        }
        public override string ToString()
        {
            return "" + empID + " " + empName + " " + email + " "+phone+" " + city + "";
        }
    }
}
